import { useAppState } from "@/context/AppContext";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { FileText, Download, Stethoscope, PiggyBank, BookOpen } from "lucide-react";

const ExportPage = () => {
  const { triageHistory, transactions, savedAmount, goal, readArticles } = useAppState();

  const generateSnapshot = () => {
    const now = new Date();
    const lines: string[] = [
      "═══════════════════════════════════════",
      "       MEDIBRIDGE HEALTH SNAPSHOT",
      "═══════════════════════════════════════",
      `Generated: ${now.toLocaleDateString()} ${now.toLocaleTimeString()}`,
      "",
      "─── TRIAGE HISTORY ───",
    ];

    if (triageHistory.length === 0) {
      lines.push("  No triage sessions recorded.");
    } else {
      triageHistory.forEach((r, i) => {
        lines.push(`  ${i + 1}. [${r.risk.toUpperCase()}] "${r.symptom}"`);
        lines.push(`     Advice: ${r.advice}`);
        lines.push(`     Next Step: ${r.nextStep}`);
        lines.push(`     Date: ${r.timestamp.toLocaleDateString()} ${r.timestamp.toLocaleTimeString()}`);
        lines.push("");
      });
    }

    lines.push("─── SAVINGS PROGRESS ───");
    lines.push(`  Goal: ₦${goal.toLocaleString()}`);
    lines.push(`  Saved: ₦${savedAmount.toLocaleString()} (${((savedAmount / goal) * 100).toFixed(1)}%)`);
    lines.push(`  Transactions: ${transactions.length}`);
    if (transactions.length > 0) {
      lines.push("  Recent:");
      transactions.slice(0, 5).forEach((tx) => {
        lines.push(`    +₦${tx.amount.toLocaleString()} on ${tx.timestamp.toLocaleDateString()} ${tx.timestamp.toLocaleTimeString()}`);
      });
    }

    lines.push("");
    lines.push("─── EDUCATION PROGRESS ───");
    lines.push(`  Guides completed: ${readArticles.size}`);
    if (readArticles.size > 0) {
      [...readArticles].forEach((a) => lines.push(`    ✓ ${a}`));
    }
    if (readArticles.size >= 3) {
      lines.push("  🏆 Badge: Community Health Champion");
    }

    lines.push("");
    lines.push("═══════════════════════════════════════");
    lines.push("  This report was generated by MediBridge AI.");
    lines.push("  Present to your healthcare provider.");
    lines.push("═══════════════════════════════════════");

    return lines.join("\n");
  };

  const handleExport = () => {
    const text = generateSnapshot();
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `medibridge-snapshot-${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="safe-bottom px-4 py-6 space-y-5">
      <div>
        <h1 className="text-xl font-bold text-foreground">Health Snapshot</h1>
        <p className="text-sm text-muted-foreground">Export your proof-of-work for a real doctor</p>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-3 gap-3">
        <Card>
          <CardContent className="flex flex-col items-center gap-1 p-4">
            <Stethoscope size={20} className="text-primary" />
            <p className="text-lg font-bold text-foreground">{triageHistory.length}</p>
            <p className="text-[10px] text-muted-foreground">Triage Sessions</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex flex-col items-center gap-1 p-4">
            <PiggyBank size={20} className="text-success" />
            <p className="text-lg font-bold text-foreground">{transactions.length}</p>
            <p className="text-[10px] text-muted-foreground">Transactions</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex flex-col items-center gap-1 p-4">
            <BookOpen size={20} className="text-warning" />
            <p className="text-lg font-bold text-foreground">{readArticles.size}</p>
            <p className="text-[10px] text-muted-foreground">Guides Read</p>
          </CardContent>
        </Card>
      </div>

      {/* Preview */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="flex items-center gap-2 text-base">
            <FileText size={16} className="text-muted-foreground" />
            Report Preview
          </CardTitle>
        </CardHeader>
        <CardContent>
          <pre className="max-h-72 overflow-auto rounded-lg bg-muted p-3 text-[11px] leading-relaxed text-foreground font-mono whitespace-pre-wrap">
            {generateSnapshot()}
          </pre>
        </CardContent>
      </Card>

      <Button onClick={handleExport} className="w-full gap-2 rounded-xl text-base font-semibold" size="lg">
        <Download size={18} />
        Export Health Snapshot
      </Button>
    </div>
  );
};

export default ExportPage;
